const fs = require('fs');

// 1. estimation.html
try {
    let est = fs.readFileSync('estimation.html', 'utf8');

    // Check if we need to add the standard navbar (since git checkout restored the old one)
    if (!est.includes('id="page-search"')) {
        console.log('Estimation needs standard navbar - run fix_navbar.js separately if needed, or we just replace the body');
    }

    // Replace the unit-tabs and est-layout
    const tabsStart = est.indexOf('<!-- Unit Tabs -->');
    let layoutEnd = est.indexOf('</div>', est.indexOf('<main class="est-main"'));
    // Need to find the closing div of est-layout
    if (tabsStart > -1) {
        const afterMain = est.substring(est.indexOf('</main>'));
        const divIdx = afterMain.indexOf('</div>');
        layoutEnd = est.indexOf('</main>') + divIdx + 6;

        const newNav = `    <!-- Internal Page Navigation -->
    <nav class="circuit-nav" id="circuit-nav">
        <ul>
            <li><a href="#unit-1" class="unit-tab active" data-unit="1">💰 Unit 1</a></li>
            <li><a href="#unit-2" class="unit-tab" data-unit="2">🏠 Unit 2</a></li>
            <li><a href="#unit-3" class="unit-tab" data-unit="3">🏭 Unit 3</a></li>
            <li><a href="#unit-4" class="unit-tab" data-unit="4">🏗️ Unit 4</a></li>
            <li><a href="#unit-5" class="unit-tab" data-unit="5">⚡ Unit 5</a></li>
            <li><a href="#unit-6" class="unit-tab" data-unit="6">🔧 Unit 6</a></li>
            <li><a href="#unit-7" class="unit-tab" data-unit="7">🧮 Unit 7</a></li>
        </ul>
    </nav>

    <!-- Main Content -->
    <main class="circuit-main" id="est-main">
        <!-- All unit sections generated by estimation.js -->
    </main>`;

        est = est.substring(0, tabsStart) + newNav + est.substring(layoutEnd);
        fs.writeFileSync('estimation.html', est, 'utf8');
        console.log('Fixed estimation.html');
    }
} catch (e) { console.error(e); }

// 2. utilization.html
try {
    let util = fs.readFileSync('utilization.html', 'utf8');

    const tabsStart = util.indexOf('<!-- Unit Tabs -->');
    if (tabsStart > -1) {
        const afterMain = util.substring(util.indexOf('</main>'));
        const divIdx = afterMain.indexOf('</div>');
        const layoutEnd = util.indexOf('</main>') + divIdx + 6;

        const newNav = `    <!-- Internal Page Navigation -->
    <nav class="circuit-nav" id="circuit-nav">
        <ul>
            <li><a href="#unit-1" class="unit-tab active" data-unit="1">🔧 Unit 1</a></li>
            <li><a href="#unit-2" class="unit-tab" data-unit="2">💡 Unit 2</a></li>
            <li><a href="#unit-3" class="unit-tab" data-unit="3">🔥 Unit 3</a></li>
            <li><a href="#unit-4" class="unit-tab" data-unit="4">🚂 Unit 4</a></li>
            <li><a href="#unit-5" class="unit-tab" data-unit="5">⚗️ Unit 5</a></li>
            <li><a href="#unit-6" class="unit-tab" data-unit="6">❄️ Unit 6</a></li>
        </ul>
    </nav>

    <!-- Main Content -->
    <main class="circuit-main" id="main-content">
        <!-- All unit sections generated by utilization.js -->
    </main>`;

        util = util.substring(0, tabsStart) + newNav + util.substring(layoutEnd);
        fs.writeFileSync('utilization.html', util, 'utf8');
        console.log('Fixed utilization.html');
    }
} catch (e) { console.error(e); }

// 3. control.html
try {
    let ctl = fs.readFileSync('control.html', 'utf8');
    if (!ctl.includes('circuit-nav')) {
        // Find navbar end to insert circuit-nav
        const navEnd = ctl.indexOf('</nav>');
        if (navEnd > -1) {
            // Wait, control.html doesn't have sections predefined in HTML, they are built by formulas.js
            // However, the user wants the section navigation
            // If control doesn't have clear sections, we can add a simple generic one or leave it
            // Let's add standard topics for control systems
            const newNav = `
    <!-- Internal Page Navigation -->
    <nav class="circuit-nav" id="circuit-nav">
        <ul>
            <li><a href="#transfer-functions">1. Transfer Functions</a></li>
            <li><a href="#time-response">2. Time Response</a></li>
            <li><a href="#stability">3. Stability</a></li>
            <li><a href="#frequency-response">4. Frequency Response</a></li>
            <li><a href="#state-space">5. State Space</a></li>
        </ul>
    </nav>`;

            ctl = ctl.substring(0, navEnd + 6) + '\n' + newNav + ctl.substring(navEnd + 6);

            // Fix main tag
            if (ctl.includes('<main id="formula-sections">')) {
                ctl = ctl.replace('<main id="formula-sections">', '<main class="circuit-main" id="formula-sections">');
            }

            fs.writeFileSync('control.html', ctl, 'utf8');
            console.log('Fixed control.html');
        }
    }
} catch (e) { console.error(e); }
